name: Deploy to cPanel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Copy build to repo folder on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/home/goregeno/algoldherbs.com/repo/"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/goregeno/algoldherbs.com/repo
            /usr/bin/uapi VersionControlDeployment create repository_root=/home/goregeno/algoldherbs.com/repo